### ISSUE TITLE
Problem with sensor "available_pv_power"

### ISSUE THREAD

**Issue by chreggy** [PatrikTrestik/homeassistant-solax-http#24] opened 2024-04-10 17:53 UTC
Hello,

I'm testing your plugin with my Solax EVC X1 and I have a sensor with, I think, wrong values.

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/17594324/86d604fa-ea17-4c2c-b52c-10cda79369bd)

Is it my Solax Boost X1 sending this ?

Thanks.

**Comment by PatrikTrestik** [comment] 2024-04-11 14:56
Is your inverter connected with EVC correctly and Green function is working?

This sensor is based on what inverter sends to charger. It does not look like real values because you probably do not have 20kW of PV power installed, or you do?

If you have CT for measurement, I'm not sure how, and if, this works. Never tested this.

**Comment by chreggy** [comment] 2024-04-11 20:53
My EVC is connected with my Inverter. Green mode is working and CT is connected to the inverter.

Green mode is not perfect and many times I have a lot of solar energy available but EVC charge is stopped.

**Comment by PatrikTrestik** [comment] 2024-04-12 08:53
It seams your setup is correct and Available PV power should work.

Value of sensor is reflecting what Invertor sends to EVC. If I simplyfy it "AvailPV=PV - HouseLoad".
EVC expects that ChargePower is included in HouseLoad. Check it it is true for you.

I suggest following observation. Watch realtime data (last 30 min).
- No charging, sunny day - you should have plenty of PV power and exporting to Grid
- See PV power, Available PV power and House Load - check if it roughly follows formula "AvailPV=PV - HouseLoad".
- Have in mind that you update sensors in HA per 15s (or as you set). But invertor calculates this every 1s.  Big spikes (electric heating, sudden cloud shade) are not reflected due to slowness.

**Comment by chreggy** [comment] 2024-04-12 09:25
Je possède un compteur numérique dans mon tableau électrique qui me donne cette information en temps réel. La courbe AvailablePower est similaire à celle que je possède déjà. Du coup je me demande s'il n'y a pas un problème de formule quelque part.

Si cet indicateur ne reflète pas un problème dans le fonctionnement du chargeur solaire, je n'en ai pas l'utilité personnellement.

**Comment by PatrikTrestik** [comment] 2024-04-12 10:16
If it corresponds to your measurement, than it is ok. 
Sensor is doing no calculation, it reflects exactly what Inverter sends to EVC. EVC uses this value for Green mode.

Formula I give you is simplified. In reality Inverter takes in account battery charging and export power limitation. Exact working is not documented.

Let me know if I can close this issue as "No issue" or if you see any problem in this sensor.

**Comment by chreggy** [comment] 2024-04-12 13:14
My GREEN mode is not working as it could be. If you say that this sensor is important for EVC, i'm in contact with SOLAX support to investigate. Grid Power sensor is OK but Grid Current is not OK.

Just to test, I changed "export control value" and the sensor is more accurate but not totally true.

Thank you. I gave you a coffee ;o)

**Comment by PatrikTrestik** [comment] 2024-04-12 14:31
If your Green mode is not working, investigate it first. HA sensors are only showing what EVC gets from Inverter. Green mode has to work completely without HA.

If you say Grid Power sensor is OK, you mean one from Inverter integration?
What is  "export control value" ? Can you post screenshot.

**Comment by chreggy** [comment] 2024-04-12 14:42
Grid Power is the value reported by EVC Plugin.

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/17594324/e50f1161-464d-412a-938c-23d8e8d7bd71)

This value is OK from the inverter but like you can see, available PV power and gris current not.

Export control value is a setting in the inverter to limit exported power to grid. If I modify this value from the default 20000 to 0 (no export), the curve of "Availability PV Power" si a little more comprehensive.

Solax on monday have updated inverter and EVC with the latest firmware but the GREEN mode is not working better.

**Comment by PatrikTrestik** [comment] 2024-04-12 15:51
Are you sure that your CT is correctly oriented? And positioned on correct place?

From value you are showing it is saying that consumption in your house is 28kW which is most probably nonsense.

Go to SolaX cloud app or web and carefully check all values if all makes sense and reflects reality.

**Comment by chreggy** [comment] 2024-04-12 16:09
I think this is OK ?

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/17594324/3fab5dd8-7462-4a7a-8108-63648feb7c35)

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/17594324/0ae89eaf-6f51-48c1-a96a-4727e924f547)

**Comment by PatrikTrestik** [comment] 2024-04-12 17:55
Few ideas.
1) Check your charger setting. It should be set to source from Inverter.
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/17616747/3916be7f-5974-4c54-bc4c-4b28eda0dd7f)
2) Check inverter setting. It has to be set to EV Charger mode.
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/17616747/a3719c1d-9872-4dd7-b91b-145d41030411)
3) Graph you show has PV Power=AC Power it is not real. In reality AC power is only compensating remaining load.
For example at 13:00 you have PV (5k)-EVC(3,6k)-House(1k)=+0,4k (should go to grid as AC (-0,4k) but you have AC +5k.

**Comment by PatrikTrestik** [comment] 2024-04-17 07:34
Let me know if you think that it is error in your setup and I can close this issue.

**Comment by PatrikTrestik** [comment] 2024-04-30 15:02
I'm closing this as installation problem, not a bug.
Feel free to comment if you still see errors in integration.

**Closed by PatrikTrestik** 2024-04-30 15:02 UTC

**Comment by chreggy** [comment] 2024-04-30 15:49
Hello.

Solax answered me that my installation is OK. They said that the problem is on the solar inverter firmware with CT and EVC. They will send me a numeric module like SDM230 to solve the problem. I will give you the result of that.
